"""auto_migration_20260624_232604

Revision ID: 2ccfc7173f75
Revises: dfad4fb1fbc3
Create Date: 2026-06-24 23:26:16.313037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ccfc7173f75'
down_revision: Union[str, None] = 'dfad4fb1fbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'auto_confirm_orders',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'auto_confirm_orders',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    # ### end Alembic commands ###
