"""add_store_customization_and_double_rating

Revision ID: 51e9910b5d3c
Revises: dd17ff7f5efd
Create Date: 2026-07-06 01:02:07.466028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e9910b5d3c'
down_revision: Union[str, None] = 'dd17ff7f5efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('store_rating', sa.Float(), nullable=False))
    op.add_column('stores', sa.Column('background_color', sa.String(length=50), nullable=True))
    op.add_column('stores', sa.Column('layout_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'layout_type')
    op.drop_column('stores', 'background_color')
    op.drop_column('reviews', 'store_rating')
    # ### end Alembic commands ###
