"""add_store_metrics_table

Revision ID: 86309e974563
Revises: 0001_initial
Create Date: 2026-06-10 15:33:37.346684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86309e974563'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('products_published', sa.Integer(), nullable=True),
    sa.Column('orders_delivered', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chat_sessions', sa.Integer(), nullable=True),
    sa.Column('template_usage', sa.Integer(), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_metrics_date'), 'store_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_store_metrics_id'), 'store_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_store_metrics_store_id'), 'store_metrics', ['store_id'], unique=False)
    op.drop_index(op.f('idx_email'), table_name='admins')
    op.drop_index(op.f('idx_username'), table_name='admins')
    op.drop_index(op.f('username'), table_name='admins')
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.drop_index(op.f('idx_parent'), table_name='categories')
    op.drop_index(op.f('idx_slug'), table_name='categories')
    op.drop_index(op.f('slug'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('categories_ibfk_1'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_constraint(op.f('fk_product_category'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('email'), table_name='stores')
    op.drop_index(op.f('idx_email'), table_name='stores')
    op.drop_index(op.f('idx_status'), table_name='stores')
    op.create_index(op.f('ix_stores_email'), 'stores', ['email'], unique=True)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_foreign_key(None, 'stores', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('BUYER', 'SELLER', 'BOTH', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'buyer'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('BUYER', 'SELLER', 'BOTH', name='userrole'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'buyer'"))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_email'), table_name='stores')
    op.create_index(op.f('idx_status'), 'stores', ['status'], unique=False)
    op.create_index(op.f('idx_email'), 'stores', ['email'], unique=False)
    op.create_index(op.f('email'), 'stores', ['email'], unique=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_category'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_ibfk_1'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('idx_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('idx_parent'), 'categories', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.create_index(op.f('username'), 'admins', ['username'], unique=True)
    op.create_index(op.f('idx_username'), 'admins', ['username'], unique=False)
    op.create_index(op.f('idx_email'), 'admins', ['email'], unique=False)
    op.drop_index(op.f('ix_store_metrics_store_id'), table_name='store_metrics')
    op.drop_index(op.f('ix_store_metrics_id'), table_name='store_metrics')
    op.drop_index(op.f('ix_store_metrics_date'), table_name='store_metrics')
    op.drop_table('store_metrics')
    # ### end Alembic commands ###
