"""Add theme to stores

Revision ID: d3ffea3a2d7d
Revises: 03e7be7c24d3
Create Date: 2026-06-19 19:21:31.002699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ffea3a2d7d'
down_revision: Union[str, None] = '03e7be7c24d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('theme', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'theme')
    # ### end Alembic commands ###
