"""Add theme to stores

Revision ID: d3ffea3a2d7d
Revises: 86309e974563
Create Date: 2026-06-19 19:21:31.002699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ffea3a2d7d'
down_revision: Union[str, None] = '86309e974563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    op.create_index('ix_admins_username', 'admins', ['username'], unique=True)
    op.add_column('stores', sa.Column('theme', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'theme')
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_index('ix_admins_id', table_name='admins')
    # ### end Alembic commands ###
