"""auto_migration_20260624_191920

Revision ID: de436e7154f1
Revises: 5b7664606ce3
Create Date: 2026-06-24 19:19:23.309780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de436e7154f1'
down_revision: Union[str, None] = '5b7664606ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_reset_codes_email', table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.add_column('addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'orders', ['delivery_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'delivery_token')
    op.drop_column('orders', 'delivery_status')
    op.drop_column('orders', 'delivery_longitude')
    op.drop_column('orders', 'delivery_latitude')
    op.drop_column('orders', 'shipping_longitude')
    op.drop_column('orders', 'shipping_latitude')
    op.drop_column('addresses', 'longitude')
    op.drop_column('addresses', 'latitude')
    op.create_table('password_reset_codes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_password_reset_codes_email', 'password_reset_codes', ['email'], unique=False)
    # ### end Alembic commands ###
