"""auto_migration_20260624_232428

Revision ID: e4d081fd758b
Revises: f0b32a0cee75
Create Date: 2026-06-24 23:24:40.670699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4d081fd758b'
down_revision: Union[str, None] = 'f0b32a0cee75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'auto_confirm_orders',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'auto_confirm_orders',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    # ### end Alembic commands ###
